version: "3.5"
networks:
  network:
services:
  server-0:
    environment:
      COUCHDB_PASSWORD: vandy2020
      COUCHDB_USER: admin
      NODENAME: couchdb-0
    image: couchdb:2.3.0
    networks:
      network:
        aliases:
          - couchdb-0.docker.com
    ports:
      - "5984:5984"
      - "5986:5986"
    volumes:
      - "volume-0:/opt/couchdb/data"

volumes:
  volume-0:
  volume-1:
  volume-2:
